### ISSUE TITLE
Modify to apply this link to the directory listing "extra fields"?

### ISSUE THREAD

**Issue by lindsayweb** [MissVeronica/um-fields-with-links#1]
Your plugin does exactly what I need, except I need it to link the field in the directory listing (not the profile page). Can it be modified to add this link to the directory extra fields?

Also, are you available for hire for a few Ultimate Member customizations?

**Comment by MissVeronica** [comment]
@lindsayweb
You can try version 2.4.0 of the plugin which supports only custom fields in the Members Directory.
UM Predefined fields are different in Members Directory and requires other settings.
I'm not available for paid support.

**Comment by lindsayweb** [comment]
Thanks! I installed the new version. Where do I find the new settings? It is a custom field I am looking to link, but I don't see a new section in the Settings > Appearance page. Here is what I have 2.4.0:

![field-links](https://github.com/MissVeronica/um-fields-with-links/assets/35513637/8f70998c-627f-4431-960d-8fc52d71bfd6)

In the memberlist template, these are the fields where I'm hoping to add the link:

```
<?php foreach ( $reveal_fields as $key ) { ?>
    <div class="um-member-metaline um-member-metaline-<?php echo $key; ?>">
	{{{user['<?php echo $key;?>']}}}
    </div>
<?php } ?>

```
Also, is there a way to stop the alert box from popping up when I click the link? It warns me to make sure the external link is safe, but it is an onsite link.

**Comment by MissVeronica** [comment]
@lindsayweb

Now I have made some code changes for Ajax calls for the Members Directory in version 2.5.0.
About  "alert box from popping up" look at the updated the documentation file [README.md](https://github.com/MissVeronica/um-fields-with-links/blob/main/README.md)

**Comment by lindsayweb** [comment]
Thanks @MissVeronica. This is adding the link to the directory. 

I do see this warning in the debug log -- sharing in case it could become an issue.

PHP Warning:  foreach() argument must be of type array|object, bool given in /wp-content/plugins/um-fields-with-links-main/um-fields-with-links.php on line 72

**Comment by MissVeronica** [comment]
Thanks!
Version 2.5.1 Code improvements
