### ISSUE TITLE
Work with multi-select fields?

### ISSUE THREAD

**Issue by lindsayweb** [MissVeronica/um-fields-with-links#2]
For multi-select fields that have multiple values, one link is applied to all of them.

My setting looks like this:

`committee_member, /members/directory/committee-members/?filter_committee_member_ecde0={value}, Filter by committee`

If a user has selected multiple values for the committee_member field, the link looks like this:

`<a href="/members/directory/committee-members/?filter_committee_member_ecde0=Journal, Membership, Nominations, Photography">`

Is it possible to separate into individual links?

**Comment by MissVeronica** [comment]
You can try Version 2.6.0  with Support for radio and checkbox UM multi fields

**Comment by MissVeronica** [comment]
Support changed to also include all UM multi fields where max selections larger than 1 in Version 2.6.1

**Comment by lindsayweb** [comment]
Thank you for the update. Unfortunately our fields are multi-select dropdown fields, which still render as a single link in 2.6.1. Are these field values possible to separate?

**Comment by lindsayweb** [comment]
Ah, I see. I must enter a number in the max selections field. I don't require a min or max for these fields, so I had nothing entered in this field. I'll just enter a large number. Thank you.

**Comment by MissVeronica** [comment]
Yes I have tested multi-select dropdowns and made a change in 2.6.2 for leading spaces in the selections.
Can you post a screencopy of your UM settings.

**Comment by lindsayweb** [comment]
@MissVeronica I think I've found a quirk with links that share the same word. 

It's a multi-select field, and there are two labels that share the word "Membership":

- Membership
- Membership News

The word "Membership" is linked to the same link for both labels. The word "News" is left unlinked:

<img width="164" src="https://github.com/MissVeronica/um-fields-with-links/assets/35513637/360ab443-369f-465f-8bf7-153b2dd64c72">

There is no issue with other values that have multiple words/spaces, so it appears to be related to the fact that they share the same word.

**Comment by MissVeronica** [comment]
Version 2.6.3 should fix this issue,

**Comment by lindsayweb** [comment]
Yes, that fixed it. Thank you!
